### ISSUE TITLE
AudioContext in Safari always 'suspended'

### ISSUE THREAD

**Issue by markfilius** [benji6/virtual-audio-graph#194]
Hi
Just asking if you have a solution to kickstart the audiocontext in Safari ?? It always starts in state 'suspended' and the usual call to resume() has no effect (so waiting for the promise or onStateChange doesnt happen).
So, like this is not helping: 
```   
    audioContext = new window.webkitAudioContext()
    audioContext.resume()
```
If you have any experience with this, I'm all ears! Thanks
Mark

EDIT
fixed, this blog helped: https://www.mattmontag.com/web/unlock-web-audio-in-safari-for-ios-and-macos
Thnaks

**Comment by benji6** [comment]
Glad you found a solution 🙂
