### ISSUE TITLE
Persisting audio graph definitions using functions

### ISSUE THREAD

**Issue by bthj** [benji6/virtual-audio-graph#267]
Hi

Using versions before [v0.20.0](https://github.com/benji6/virtual-audio-graph/releases/tag/v0.20.0), where audio graphs are defined as arrays, it's easy to save the definitions, in e.g. a document database.  But after the change to using functions for the audio graph definitions, I'm unsure how to go about persisting them:  

Any ideas on how to achieve that?

**Comment by benji6** [comment]
Apologies if I broke anything with this change, I didn't actually think anyone would have this usecase. Some graphs probably don't translate well to storing server-side - especially when they make use of timing. Would be interested to hear more about how you're using the library?

I think that it would be very straightforward to create a little DSL to get around this issue. For instance if you want to store this graph on the server:

```js
virtualAudioGraph.update({
  0: gain('output', { gain: 0.5 }),
  1: oscillator(0),
})
```
You could store a data structure like:

```js
const audioGraph = {
  0: ['gain', 'output', { gain: 0.5 }],
  1: ['oscillator', 0]
}
```

Then use a function that compiles that to a format that virtual-audio-graph understands:

```js
import * as nodes from 'virtual-audio-graph'

const compileAudioGraph = (audioGraph) => Object.fromEntries(
  Object.entries(audioGraph)
    .map(([key, [nodeName, ...nodeArgs]]) => [key, nodes[nodeName](...nodeArgs)])
)

virtualAudioGraph.update(compileAudioGraph(audioGraph))
```

Haven't actually run that code, but something like that should work. Does that make sense?

**Comment by bthj** [comment]
Yes, that makes sense.  Thanks for the example compilation function - and no worries about the breaking change, that was clearly documented in the release notes, just wondering if I should stay on < v0.20.0, while it would be good to sync with the latest bugfixes and it's interesting to try out the support for AudioWorklets.  That mapping function could be the way to go.

I'm using this library for the [synth.is](https://synth.is/) pet project, where it has been super helpful - Thanks! - [intro video](https://www.youtube.com/watch?v=dm2cgPqQVP0) and [another](https://youtu.be/3eLo8qORiMQ).  Haven't been working on this in the past months but hope to find time for another iteration soon, where I would need to revisit the usage of virtual-audio-graph.  [PauchDB](https://pouchdb.com/) is used for local persistence (initial plan was to use the sync features it offers but that was abandoned and now it's just persisting to [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)) but when audio signal patches are published at synth.is, they are saved in [MinIO](https://min.io/) buckets as plain text files.

**Comment by benji6** [comment]
Cool project!

**Comment by bthj** [comment]
Hey @benji6, and happy holidays 🎄

I'm still using that [v0.19.9](https://github.com/benji6/virtual-audio-graph/releases/tag/v0.19.9) tag and just made one modification which you might be interested in for the current version of this project:

https://github.com/synth-is/virtual-audio-graph/commit/40da5c2f1b2150e82ef1058d567b973669e47b6a

- [the Web Audio API implementation I'm trying out](https://github.com/ircam-ismm/node-web-audio-api) didn't work when the `offsetTime` parameter was passed to the [start method of an oscillator node](https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start).

**Comment by benji6** [comment]
Hi @bthj, thanks for the holiday wishes, hope you had a good time! Apologies for the delay in my response. 

OscillatorNodes don't support offset time and it is not listed as supported in the docs. With AudioBufferSourceNodes the offset specifies the offset that the audio clip starts at.

When I try to pass a second parameter to an OscillatorNode start method I'm observing no errors and the node works the same way as if I had passed a single parameter to the start method. I'm not sure how your proposed change will affect the behavior of the library in that case?

**Comment by bthj** [comment]
Hi @benji6 - the change I made there to the `v0.19.9` code was necessary to have `virtual-audio-graph` working with the [node-web-audio-api](https://github.com/ircam-ismm/node-web-audio-api) implementation. A similar modification to the current `virtual-audio-graph` code might be interesting, so it may work with non-browser implementations like that one. Actually I haven't yet tried the current version with `node-web-audio-api`, only assuming the same applies :)

**Comment by benji6** [comment]
Ah I see! I had not tested it with node-web-audio-api - seems like the implementation is different than in the browser. This issue definitely existed in the latest release. I have just pushed a fix https://github.com/benji6/virtual-audio-graph/commit/f898b0988b3c569ddf92178e5f87a1fb3da875a9. Latest release should work https://github.com/benji6/virtual-audio-graph/releases/tag/v1.1.9. Thanks for flagging this :)
