### ISSUE TITLE
Access to currently playing sound?

### ISSUE THREAD

**Issue by markfilius** [benji6/virtual-audio-graph#276]
Hi Benji6,
I'm building an app to apply filters to soundtracks in order to imitate the world of the hearing impaired. 
It'd be nice to do that to the _currently_ playing sound in a browser, so from another app or source. Is there any way I can access that sound (without going through the microphone) ??
Likely not - it would be a security issue - but I'm just checking anyway.
Thanks
Mark

**Comment by benji6** [comment]
This isn't something I've tried to do before, but if I was you I'd see if you can do something like this with a browser extension - they typically give you a lot of extra control and allow you to inject code into other websites. I'm not sure if there's a clean way to achieve this though

**Comment by markfilius** [comment]
Thanks, I'll look at extensions. I'd be very surprised if there is a clean way - we can but try :-)
