### ISSUE TITLE
Support multiple inputs and outputs

### ISSUE THREAD

**Issue by mbylstra** [benji6/virtual-audio-graph#28]
Unless I've missed something, there doesn't seem to be support for AudioNodes that have multiple inputs or outputs such as ChannelSplitterNode (https://developer.mozilla.org/en-US/docs/Web/API/ChannelSplitterNode) and ChannelMergerNode (https://developer.mozilla.org/en-US/docs/Web/API/ChannelMergerNode).

This is essential for stereo effects.

With the current design, by using an array you can route a mono output to multiple different nodes (which have mono inputs), but for a node that supports multiple inputs (stereo, 6 channel surround, etc), there is no way of specifying the specific input to connect the output to.

For example, here is an example stereo delay using the Web Audio API:
https://github.com/web-audio-components/delay/blob/master/index.js#L154.
In this example, the first output of `rightFilter` is connected to the second input of `_merge` ( a ChannelMergerNode that takes two inputs in this configuration).

**Comment by mbylstra** [comment]
Sorry, I missed this part of the documentation: https://github.com/benji6/virtual-audio-graph#channelsplitternode. I see how you've implemented it now.

**Comment by benji6** [comment]
No worries! Let me know if you have any questions or ideas on improving the documentation or the API!

**Comment by voodoohop** [comment]
@benji6 I can't figure out how to use the channelSplitter. When I just specify the output by just passing the key of the node I want to connect to it works but I cannot seem to get it connect with the `{key, inputs, outputs}` parameter. Any chance of an example code?

**Comment by benji6** [comment]
Hi @voodoohop, I think you have found the limited documentation here https://github.com/benji6/virtual-audio-graph/blob/master/docs/standard-nodes.md#channelsplitter.

`key` refers to the virtual node key you specify when you configure the graph and the `inputs` and `outputs` values are passed to the 2nd and 3rd arguments of the `connect` method under the hood https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect 

Are you splitting something that has multiple channels? Sorry to flip this around, but do you have an example I can take a look at and help debug?

**Comment by voodoohop** [comment]
Thanks for your reply! 

I think I'm using the syntax correctly but not 100% sure yet. What I'm doing is first splitting and then merging so I can map a number of stereo channels playing samples arbitrarily to the audio device output channels.

Love the idea behind your library. I'm prototyping a loop-based music-making app for the company that makes https://korus.co/. 

https://layermosaic.pixelynx-ai.com/

I spent a day porting the code to use virtual-audio-graph and the whole design is going to be so much cleaner and simpler thanks to it.

I'm going to try and create a test case for this. Seems like the most efficient way to document my problem.
