### ISSUE TITLE
Code in custom node is interpreted in a different way

### ISSUE THREAD

**Issue by Nek** [benji6/virtual-audio-graph#316]
Hi, the name of the bug is actually an assumption. I have isolated the problem in two code sandboxes.

This works perfectly fine. Top level audio graph definition is updated on setInterval:
https://codesandbox.io/s/relaxed-ramanujan-7qdmr?file=/src/index.js

This one doesn't work as expected. Seemingly, the same code produces only two events:
https://codesandbox.io/s/elegant-heisenberg-leht2?file=/src/index.js

I do hope it's my mistake, but I can't find it.

Otherwise, thanks for the great work. I'm having a crush on this library and going to base my audio experiments on it (replacing tonejs, that does too much).

**Comment by benji6** [comment]
Hi @Nek, I've taken a look at this and it looks like a bug in virtual-audio-graph.

The oscillator node that is created using the Web Audio API will not start again once you have stopped it. The library handles this with normal audio nodes (https://github.com/benji6/virtual-audio-graph/blob/master/src/VirtualAudioGraph.ts#L41), but there is no special handling of this for custom audio nodes - hence the bug you found. I will have a think about what a fix looks like.

**Comment by Nek** [comment]
@benji6 Thanks!

**Comment by benji6** [comment]
@Nek found some time to take a proper look at this. I cannot think of any easy way to unit test it with the audio testing library I'm using so I tested manually and just released v1.1.7 (https://github.com/benji6/virtual-audio-graph/releases/tag/v1.1.7). I ran your code sandbox with the new version and it seems to work for me. If you're happy we can close the issue.

**Comment by Nek** [comment]
Thanks a lot! It's all good as long as it works.
