### ISSUE TITLE
Custom Nodes and AudioWorklets

### ISSUE THREAD

**Issue by MVSICA-FICTA** [benji6/virtual-audio-graph#39]
Really liking the declarative configurable functional way virtual-audio-graph works. An AudioWorklet is yet another type of custom node, can virtual-audio-graph integrate them?

**Comment by benji6** [comment]
Thanks! Yeah I think it's possible. I'm not sure what the API should be though. My initial thought is to let the user call `addModule` themselves and provide something like a `createWorkletNode` function that is called with the worklet node's name and returns a virtual audio node creator function that works in the same way as all the standard ones provided (e.g. `oscillator`, `gain` etc.):

```js
const audioContext = new AudioContext()

const virtualAudioGraph = createVirtualAudioGraph({audioContext})

audioContext.audioWorklet.addModule('my-node.js').then(() => {
  const myNode = createWorkletNode('my-node')

  virtualAudioGraph.update({
    0: myNode('output'),
    1: oscillator(0),
  })
})
```

I'm a bit unsure about how testing is going to work for this as I've been using https://github.com/mohayonao/web-audio-test-api and it doesn't look like it has AudioWorklet support so will have to have a think about that 🤔 

What do you think about the API though? Any suggestions?

**Comment by MVSICA-FICTA** [comment]
Looks like a fine integration, nicer than I had expected 😄

**Comment by benji6** [comment]
Cheers, when I've got a bit of spare time I'll start looking at building it!

**Comment by MVSICA-FICTA** [comment]
Awesome! So the way I understand this is that an AudioWorklet can be used in a virtual-audio-graph like any other audio node and connected to other AudioContext nodes. Does this also allow the params the AudioWorklet might expose to be updated by the `virtualAudioGraph.update` function? 

Have you seen Genish.js? Looks like it will also be able to work with AudioWorklets according to https://github.com/charlieroberts/genish.js/issues/8

**Comment by benji6** [comment]
Hey, yep that's exactly how I envision it working!

And I've not seen Genish.js before - looks really cool, thanks for sharing :)

**Comment by benji6** [comment]
Hey! I've added support for AudioWorklets now. It's working in the new documentation, but I am lacking unit test coverage atm. I don't think that's a major issue right now because it's so new and experimental so can come back to that later! Thanks for raising the issue and let me know if you have any questions! :)
