### ISSUE TITLE
Support OfflineAudioContext (repeat #8)

### ISSUE THREAD

**Issue by jiangts** [benji6/virtual-audio-graph#397]
Looking to do some audio processing with WebAudio API and need OfflineAudioContext to do it!

Tried forking the library and contributing myself, but honestly I never got into typescript... started changing types wholesale from `AudioContext` to `AudioContext | OfflineAudioContext` and then the ts compiler started yelling at me for an unrelated type issue. 

Beats me, honestly... It wasn't satisfied even after my `any` typecast :( Guess I'm too dumb to prove all this stuff to the compiler lol

**Comment by benji6** [comment]
Hi @jiangts, I opened #8 almost 5 years ago now and never implemented it!

I have quite limited time atm, but I can have a look at what this might require and think about the best approach. Clearly some people would find it useful

**Comment by benji6** [comment]
@jiangts support should be added in the latest version https://github.com/benji6/virtual-audio-graph/releases/tag/v1.2.0. I added a section right at the end of the [docs](https://virtual-audio-graph.netlify.app/) with an example. Please let me know if you have any questions

**Comment by jiangts** [comment]
Thank you! Really appreciate this -- I looked at your changes and that's what I did in my fork, but I guess my typescript configs were off(?) VSCode kept giving me errors anyhow. And thanks, I'll try it out!
