### ISSUE TITLE
How to use in browser.

### ISSUE THREAD

**Issue by agorangetek** [benji6/virtual-audio-graph#407]
Hi, probably a simple answer to this but I cant find a .js file to include so that I can start using this. I am not sure how to do the import stuff. Can someone help me?

**Comment by benji6** [comment]
Hi, you will need to install via a package manager (here are the instructions on how to use [npm](https://www.npmjs.com/) https://github.com/benji6/virtual-audio-graph#installation) then you will need to use a bundler (loads to choose from, [parcel](https://parceljs.org/) is very easy to get started with, [webpack](https://webpack.js.org/) is very popular, and there are loads of other options out there).

If you are new to this sort of thing I recommend searching online for how to use npm modules in the browser - there are lots of tutorials that will explain much better than me. Hope that is helpful!

**Comment by agorangetek** [comment]
Thanks
