### ISSUE TITLE
v1.1.1 release don't include the compiled module

### ISSUE THREAD

**Issue by aratama** [benji6/virtual-audio-graph#45]
Hello, 

The latest `v1.1.1` npm package don't include `dist/index.js` and I failed building my app. I needed to do `cd node_modules/virtual-audio-graph`, `npm i -g rollup` and  ` npm run build` to build.  `v1.1.0` includes `dist/index.js`. Could you fix it?

**Comment by benji6** [comment]
Sorry about this, I don't really know how it happened, something may have changed with semantic-release or Travis, looks like the build step wasn't running before publish but that should be resolved in the latest release now
