### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by chr15m** [benji6/virtual-audio-graph#475]
I wonder if it's worth deploying this on GitHub pages? You can do it in the settings by setting the published branch to "master" and the folder to "/docs". I did a test deploy here and it works well:

https://chr15m.github.io/virtual-audio-graph/

**Comment by chr15m** [comment]
Oh hang on, it's missing the `main.js`.

**Comment by benji6** [comment]
A while back Netlify migrated from the `.com` TLD to `.app` and I didn't update the links in the repo and the documentation. This should be fixed now. Please reopen if you encounter any further issues. Thank you for spotting this and reporting it!

**Comment by chr15m** [comment]
Hi Ben, just a heads-up this seems to have broken again.

**Comment by benji6** [comment]
https://virtual-audio-graph.netlify.app seems to be working for me. Can you confirm that's the URL you were using?

**Comment by chr15m** [comment]
Ah yep, sorry for the noise! I was visiting the old one from my history. :facepalm:
