### ISSUE TITLE
Example connect to a source from a file

### ISSUE THREAD

**Issue by markfilius** [benji6/virtual-audio-graph#66]
Hi

I'm trying to implement the library to filter existing sound tracks (as examples of hearing loss).
But I'm having having trouble finding the correct method to load an existing audio file so that I can apply the biquad (notch) filter. Where can I find examples where existing files are loaded and used as input for this library?

Thanks
Mark

**Comment by benji6** [comment]
Hi, I don't currently have any documentation on how to do this, but something like this should work:

```
async function example() {
  const audioContext = new AudioContext()
  const virtualAudioGraph = createVirtualAudioGraph({ audioContext })

  const response = await fetch('my-audio-sample.wav')
  const data = await response.arrayBuffer()
  const buffer = await audioContext.decodeAudioData(data)

  virtualAudioGraph.update({
    0: gain('output', { gain: 0.2 }),
    1: bufferSource(0, { buffer }),
  })
}
```

There's some more info on the buffer source node here: https://github.com/benji6/virtual-audio-graph/blob/master/docs/standard-nodes.md#buffersource

Over the next few days I'll look at adding an example to the docs to help with this sort of usecase

**Comment by markfilius** [comment]
Awesome! Thanks!


On 22 Jul 2019, at 07:01, Ben Hall <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I don't currently have any documentation on how to do this, but something like this should work:

async function example() {
  const audioContext = new AudioContext()
  const virtualAudioGraph = createVirtualAudioGraph({ audioContext })

  const response = await fetch('my-audio-sample.wav')
  const data = await response.arrayBuffer()
  const buffer = await audioContext.decodeAudioData(data)

  virtualAudioGraph.update({
    0: gain('output', { gain: 0.2 }),
    1: bufferSource(0, { buffer }),
  })
}


There's some more info on the buffer source node here: https://github.com/benji6/virtual-audio-graph/blob/master/docs/standard-nodes.md#buffersource

Over the next few days I'll look at adding an example to the docs to help with this sort of usecase

**Comment by benji6** [comment]
I've added a bit in the docs on working with audio files now so people in the future should find it a bit easier (f96fa5f3a2dc122c3889ea31e8a50416bea782dd) thanks for the feedback, let me know if you have any other issues!

**Comment by markfilius** [comment]
Thanks :-)

I’m away this week - when I have a chance I’ll look and give you feedback. cheers


On 23 Jul 2019, at 00:25, Ben Hall <notifications@github.com<mailto:notifications@github.com>> wrote:


I've added a bit in the docs on working with audio files now so people in the future should find it a bit easier (f96fa5f<https://github.com/benji6/virtual-audio-graph/commit/f96fa5f3a2dc122c3889ea31e8a50416bea782dd>) thanks for the feedback, let me know if you have any other issues!

**Comment by markfilius** [comment]
Hi Ben,

I have implemented the audio graph, inspired by your example. Audio is a new world for me and took a bit of experimentation, but it works a treat. Fyi, the actual code is aded below. Basically a file object (stored in a database) is read into an arrayBuffer, converted to audioBuffer and added into the audio graph.

That has led me to one more question: how can I change the graph on-the-fly, ie while audio is playing? The declarative nature allows a detailed setup, but changing the graph with .update() after some event doesn't do what I hope. Basically I'd like the user to control (through a button click) whether the biquadFilter is applied or not.

Any advice is appreciated!
Thanks
Mark

                // After reading file soundtrack file....
                fileReader.onload = (event) => {
                    if (!event) return null

                    const arrayBuffer = fileReader.result
                    if (!arrayBuffer || typeof arrayBuffer === 'string') {
                        console.log('arrayBuffer not expected format:', arrayBuffer)
                        return null
                    }

                    // ... convert the arrayBuffer to an audioBuffer, and ....
                    audioContext.decodeAudioData(arrayBuffer)
                        .then((buffer: any) => {

                            // ... play
                            virtualAudioGraph.update({
                                0: gain('output', {gain: 1}),
                                1: biquadFilter(0, {
                                    type: 'notch',
                                    frequency: 1000,
                                }),
                                2: bufferSource(1, {buffer}),
                            })

                        })
                        .catch((response: Error) => {
                            console.log('decode error', response)
                        })
                }

                // Start the actual read
                fileReader.readAsArrayBuffer(file)
