### ISSUE TITLE
VAG samples not working in safari

### ISSUE THREAD

**Issue by catz** [benji6/virtual-audio-graph#74]
Hello Ben,

I tried examples from https://virtual-audio-graph.netlify.com in safari (12.1.2) today and none of them worked. 

I see this in console.
ReferenceError: Can't find variable: AudioContext

**Comment by benji6** [comment]
In Safari `AudioContext` is still vendor prefixed so if you want to support it you have to do something like this:

```js
const AudioContext = window.AudioContext || window.webkitAudioContext
const audioContext = new AudioContext()
const virtualAudioGraph = createVirtualAudioGraph({ audioContext })
```

I've updated the docs so the examples should work in Safari now

**Comment by catz** [comment]
Ben I still recommend to reopen this ticket and check all samples on this page. For example last sample gives me "Error: Unknown node type: stereoPanner". The previous one - TypeError: undefined is not an object (evaluating 'audioContext.audioWorklet
            .addModule')

I understand that API between chrome/safari is different but you may disable play button or add some note for safari for nodes like stereoPanner ?

**Comment by benji6** [comment]
Ah I didn't check all the examples, it may be that some are not supported in Safari, I'll have to have a look into this

**Comment by benji6** [comment]
Safari doesn't actually support StereoPannerNode (https://developer.mozilla.org/en-US/docs/Web/API/StereoPannerNode#Browser_compatibility) so that's why that example doesn't work.

The Web Audio API is still relatively new and doesn't work in older browsers. As most devs don't use Safari I think I'm OK with using StereoPannerNode in the docs right now

**Comment by catz** [comment]
yeah, a simple note in docs about browsers support can be enough I guess.

**Comment by benji6** [comment]
Does #75 look OK to you?

**Comment by catz** [comment]
looks good to me
